### ISSUE TITLE
Example Fails to Run on Windows 11: Missing Step or Configuration Issue

### ISSUE THREAD

**Issue by zardamhussain** [daily-co/daily-core-sdk#1]
![image](https://github.com/user-attachments/assets/9d44d3e0-6057-4bfe-984f-24732b0a671b)

**Comment by aconchillo** [comment]
Hi! This will happen if `DAILY_CORE_PATH` environment variable is not set properly. It needs to point to where you extracted `daily-core-sdk`. For example:

```
set DAILY_CORE_PATH=C:\Users\YOUR_USER\Source\daily-core-sdk-0.11.0
```

**Comment by zardamhussain** [comment]
Thank you, @aconchillo . I was able to successfully run the setup after your guidance. However, I wasn't able to locate any documentation specifically related to the C++ implementation. Could you point me in the right direction or share any available resources that would assist me with this? Your help has been invaluable, and any further guidance on this matter would be greatly appreciated!
